module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.4.2-stable-13.09
cabal-file: project.cabal
hidden-packages: ''
version: 1
extra-packages: ! 'Hackage: bindings-DSL 1.0.20

  Hackage: bzlib-conduit 0.2.1.1

'
ghc-args: []
excluded-modules: []
